version: "3.7"

services:
  # Laravel application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - db
      - redis
    networks:
      - laravel

  # Nginx server
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8589:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel

  # MySQL database
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: inovedashboad
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: Lazaro
    ports:
      - "3521:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    restart: always
    networks:
      - laravel

  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root  # Adjust if necessary
    networks:
      - laravel

  # Redis server
  redis:
    image: redis:latest
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  db_data:
    driver: local
